# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for smultron configurations
Name: jolla-configuration-smultron
Requires:
- pattern:jolla-hw-adaptation-smultron
- pattern:jolla-configuration-2011xperia

Summary: Jolla Configuration smultron
