Description: Pattern with packages for satsuma configurations
Name: jolla-configuration-satsuma
Requires:
- pattern:jolla-hw-adaptation-satsuma
- pattern:jolla-configuration-2011xperia

Summary: Jolla Configuration satsuma
