# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for haida configurations
Name: jolla-configuration-haida
Requires:
- patterns-sailfish-device-configuration-haida

Summary: Jolla Configuration haida
