Description: Pattern with packages for coconut configurations
Name: jolla-configuration-coconut
Requires:
- pattern:jolla-hw-adaptation-coconut
- pattern:jolla-configuration-2011xperia

Summary: Jolla Configuration coconut
