Description: Pattern with packages for smultron configurations
Name: jolla-configuration-smultron
Requires:
- pattern:jolla-hw-adaptation-smultron
- pattern:jolla-configuration-2011xperia

Summary: Jolla Configuration smultron
