Description: Pattern with packages for anzu configurations
Name: jolla-configuration-anzu
Requires:
- pattern:jolla-hw-adaptation-anzu
- pattern:jolla-configuration-2011xperia

Summary: Jolla Configuration anzu
