# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for urushi configurations
Name: jolla-configuration-urushi
Requires:
- patterns-sailfish-device-configuration-urushi

Summary: Jolla Configuration urushi
