Description: Pattern with packages for iyokan configurations
Name: jolla-configuration-iyokan
Requires:
- pattern:jolla-hw-adaptation-iyokan
- pattern:jolla-configuration-2011xperia

Summary: Jolla Configuration iyokan
