# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for anzu configurations
Name: jolla-configuration-anzu
Requires:
- pattern:jolla-hw-adaptation-anzu
- pattern:jolla-configuration-2011xperia

Summary: Jolla Configuration anzu
