Description: Pattern with packages for hallon configurations
Name: jolla-configuration-hallon
Requires:
- pattern:jolla-hw-adaptation-hallon
- pattern:jolla-configuration-2011xperia

Summary: Jolla Configuration hallon
