Description: Pattern with packages for haida configurations
Name: jolla-configuration-haida
Requires:
- pattern:jolla-hw-adaptation-haida
- pattern:jolla-configuration-2011xperia

Summary: Jolla Configuration haida
