Description: Pattern with packages for urushi configurations
Name: jolla-configuration-urushi
Requires:
- pattern:jolla-hw-adaptation-urushi
- pattern:jolla-configuration-2011xperia

Summary: Jolla Configuration urushi
