%package -n patterns-sailfish-device-configuration-hallon
Summary: Jolla Configuration hallon
Requires: patterns-sailfish-device-configuration-common-hallon
Requires: patterns-sailfish-device-adaptation-hallon
#Requires: patterns-sailfish-device-configuration-2011xperia

%description -n patterns-sailfish-device-configuration-hallon
Pattern with packages for hallon configurations

%files -n patterns-sailfish-device-configuration-hallon
