%package -n patterns-sailfish-device-configuration-mango
Summary: Jolla Configuration mango
Requires: patterns-sailfish-device-configuration-common-mango
Requires: patterns-sailfish-device-adaptation-mango
#Requires: patterns-sailfish-device-configuration-2011xperia

%description -n patterns-sailfish-device-configuration-mango
Pattern with packages for mango configurations

%files -n patterns-sailfish-device-configuration-mango
