%package -n patterns-sailfish-device-configuration-coconut
Summary: Jolla Configuration coconut
Requires: patterns-sailfish-device-configuration-common-coconut
Requires: patterns-sailfish-device-adaptation-coconut
#Requires: patterns-sailfish-device-configuration-2011xperia

%description -n patterns-sailfish-device-configuration-coconut
Pattern with packages for coconut configurations

%files -n patterns-sailfish-device-configuration-coconut
