%package -n patterns-sailfish-device-configuration-haida
Summary: Jolla Configuration haida
Requires: patterns-sailfish-device-configuration-common-haida
Requires: patterns-sailfish-device-adaptation-haida
#Requires: patterns-sailfish-device-configuration-2011xperia

%description -n patterns-sailfish-device-configuration-haida
Pattern with packages for haida configurations

%files -n patterns-sailfish-device-configuration-haida
