%package -n patterns-sailfish-device-configuration-anzu
Summary: Jolla Configuration anzu
Requires: patterns-sailfish-device-configuration-common-anzu
Requires: patterns-sailfish-device-adaptation-anzu
#Requires: patterns-sailfish-device-configuration-2011xperia

%description -n patterns-sailfish-device-configuration-anzu
Pattern with packages for anzu configurations

%files -n patterns-sailfish-device-configuration-anzu
