%package -n patterns-sailfish-device-configuration-urushi
Summary: Jolla Configuration urushi
Requires: patterns-sailfish-device-configuration-common-urushi
Requires: patterns-sailfish-device-adaptation-urushi
#Requires: patterns-sailfish-device-configuration-2011xperia

%description -n patterns-sailfish-device-configuration-urushi
Pattern with packages for urushi configurations

%files -n patterns-sailfish-device-configuration-urushi
