%package -n patterns-sailfish-device-ui-configuration-2011xperia
Summary: Jolla UI Configuration 2011 Xperias
Requires: jolla-ambient-z%{icon_res}
Requires: ambient-icons-closed-z%{icon_res}

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
Requires: jolla-settings-accounts-extensions-3rd-party-all

%description -n patterns-sailfish-device-ui-configuration-2011xperia
Pattern with UI related packages for 2011 Xperia configurations

%files -n patterns-sailfish-device-ui-configuration-2011xperia
