%package -n patterns-sailfish-device-adaptation-coconut
Summary: Jolla HW Adaptation coconut
Requires: patterns-sailfish-device-configuration-common-coconut
Requires: patterns-sailfish-device-adaptation-2011xperia

Requires: droid-hal-coconut
Requires: droid-hal-coconut-img-boot
Requires: droid-hal-coconut-kernel-modules
Requires: droid-config-coconut-sailfish
Requires: droid-config-coconut-pulseaudio-settings
Requires: droid-config-coconut-policy-settings
Requires: droid-config-coconut-preinit-plugin
Requires: droid-hal-version-coconut

%description -n patterns-sailfish-device-adaptation-coconut
Pattern with packages for coconut HW Adaptation

%files -n patterns-sailfish-device-adaptation-coconut
