%package -n patterns-sailfish-device-configuration-2011xperia
Summary: Jolla Configuration 2011xperia
#Requires: jolla-sailfish-applications
#Requires: jolla-ui-wayland
Requires: patterns-sailfish-device-configuration-common-2011xperia
Requires: patterns-sailfish-device-adaptation-haida
# Early stages of porting benefit from these:
#Requires: sailfish-porter-tools

%description -n patterns-sailfish-device-configuration-2011xperia
Pattern with packages for 2011 Xperia configurations

%files -n patterns-sailfish-device-configuration-2011xperia
