%package -n patterns-sailfish-device-adaptation-satsuma
Summary: Jolla HW Adaptation satsuma
Requires: patterns-sailfish-device-configuration-common-satsuma
Requires: patterns-sailfish-device-adaptation-2011xperia

Requires: droid-hal-satsuma
Requires: droid-hal-satsuma-img-boot
Requires: droid-hal-satsuma-kernel-modules
Requires: droid-config-satsuma-sailfish
Requires: droid-config-satsuma-pulseaudio-settings
Requires: droid-config-satsuma-policy-settings
Requires: droid-config-satsuma-preinit-plugin
Requires: droid-hal-version-satsuma

%description -n patterns-sailfish-device-adaptation-satsuma
Pattern with packages for satsuma HW Adaptation

%files -n patterns-sailfish-device-adaptation-satsuma
