%package -n patterns-sailfish-device-configuration-smultron
Summary: Jolla Configuration smultron
Requires: patterns-sailfish-device-configuration-common-smultron
Requires: patterns-sailfish-device-adaptation-smultron
#Requires: patterns-sailfish-device-configuration-2011xperia

%description -n patterns-sailfish-device-configuration-smultron
Pattern with packages for smultron configurations

%files -n patterns-sailfish-device-configuration-smultron
