%package -n patterns-sailfish-device-adaptation-anzu
Summary: Jolla HW Adaptation anzu
Requires: patterns-sailfish-device-configuration-common-anzu
Requires: patterns-sailfish-device-adaptation-2011xperia

Requires: droid-hal-anzu
Requires: droid-hal-anzu-img-boot
Requires: droid-hal-anzu-kernel-modules
Requires: droid-config-anzu-sailfish
Requires: droid-config-anzu-pulseaudio-settings
Requires: droid-config-anzu-policy-settings
Requires: droid-config-anzu-preinit-plugin
Requires: droid-hal-version-anzu

%description -n patterns-sailfish-device-adaptation-anzu
Pattern with packages for anzu HW Adaptation

%files -n patterns-sailfish-device-adaptation-anzu
