%package -n patterns-sailfish-device-adaptation-hallon
Summary: Jolla HW Adaptation hallon
Requires: patterns-sailfish-device-configuration-common-hallon
Requires: patterns-sailfish-device-adaptation-2011xperia

Requires: droid-hal-hallon
Requires: droid-hal-hallon-img-boot
Requires: droid-hal-hallon-kernel-modules
Requires: droid-config-hallon-sailfish
Requires: droid-config-hallon-pulseaudio-settings
Requires: droid-config-hallon-policy-settings
Requires: droid-config-hallon-preinit-plugin
Requires: droid-hal-version-hallon

%description -n patterns-sailfish-device-adaptation-hallon
Pattern with packages for hallon HW Adaptation

%files -n patterns-sailfish-device-adaptation-hallon
