%package -n patterns-sailfish-device-adaptation-urushi
Summary: Jolla HW Adaptation urushi
Requires: patterns-sailfish-device-configuration-common-urushi
Requires: patterns-sailfish-device-adaptation-2011xperia

Requires: droid-hal-urushi
Requires: droid-hal-urushi-img-boot
Requires: droid-hal-urushi-kernel-modules
Requires: droid-config-urushi-sailfish
Requires: droid-config-urushi-pulseaudio-settings
Requires: droid-config-urushi-policy-settings
Requires: droid-config-urushi-preinit-plugin
Requires: droid-hal-version-urushi

%description -n patterns-sailfish-device-adaptation-urushi
Pattern with packages for urushi HW Adaptation

%files -n patterns-sailfish-device-adaptation-urushi
