%package -n patterns-sailfish-device-configuration-satsuma
Summary: Jolla Configuration satsuma
Requires: patterns-sailfish-device-configuration-common-satsuma
Requires: patterns-sailfish-device-adaptation-satsuma
#Requires: patterns-sailfish-device-configuration-2011xperia

%description -n patterns-sailfish-device-configuration-satsuma
Pattern with packages for satsuma configurations

%files -n patterns-sailfish-device-configuration-satsuma
