%package -n patterns-sailfish-device-adaptation-smultron
Summary: Jolla HW Adaptation smultron
Requires: patterns-sailfish-device-configuration-common-smultron
Requires: patterns-sailfish-device-adaptation-2011xperia

Requires: droid-hal-smultron
Requires: droid-hal-smultron-img-boot
Requires: droid-hal-smultron-kernel-modules
Requires: droid-config-smultron-sailfish
Requires: droid-config-smultron-pulseaudio-settings
Requires: droid-config-smultron-policy-settings
Requires: droid-config-smultron-preinit-plugin
Requires: droid-hal-version-smultron

%description -n patterns-sailfish-device-adaptation-smultron
Pattern with packages for smultron HW Adaptation

%files -n patterns-sailfish-device-adaptation-smultron
