%package -n patterns-sailfish-device-configuration-iyokan
Summary: Jolla Configuration iyokan
Requires: patterns-sailfish-device-configuration-common-iyokan
Requires: patterns-sailfish-device-adaptation-iyokan
#Requires: patterns-sailfish-device-configuration-2011xperia

%description -n patterns-sailfish-device-configuration-iyokan
Pattern with packages for iyokan configurations

%files -n patterns-sailfish-device-configuration-iyokan
