%package -n patterns-sailfish-device-adaptation-haida
Summary: Jolla HW Adaptation haida
Requires: patterns-sailfish-device-configuration-common-haida
Requires: patterns-sailfish-device-adaptation-2011xperia

Requires: droid-hal-haida
Requires: droid-hal-haida-img-boot
Requires: droid-hal-haida-kernel-modules
Requires: droid-config-haida-sailfish
Requires: droid-config-haida-pulseaudio-settings
Requires: droid-config-haida-policy-settings
Requires: droid-config-haida-preinit-plugin
Requires: droid-hal-version-haida

%description -n patterns-sailfish-device-adaptation-haida
Pattern with packages for haida HW Adaptation

%files -n patterns-sailfish-device-adaptation-haida
