%package -n patterns-sailfish-device-adaptation-mango
Summary: Jolla HW Adaptation mango
Requires: patterns-sailfish-device-configuration-common-mango
Requires: patterns-sailfish-device-adaptation-2011xperia

Requires: droid-hal-mango
Requires: droid-hal-mango-img-boot
Requires: droid-hal-mango-kernel-modules
Requires: droid-config-mango-sailfish
Requires: droid-config-mango-pulseaudio-settings
Requires: droid-config-mango-policy-settings
Requires: droid-config-mango-preinit-plugin
Requires: droid-hal-version-mango

%description -n patterns-sailfish-device-adaptation-mango
Pattern with packages for mango HW Adaptation

%files -n patterns-sailfish-device-adaptation-mango
