%package -n patterns-sailfish-device-adaptation-iyokan
Summary: Jolla HW Adaptation iyokan
Requires: patterns-sailfish-device-configuration-common-iyokan
Requires: patterns-sailfish-device-adaptation-2011xperia

Requires: droid-hal-iyokan
Requires: droid-hal-iyokan-img-boot
Requires: droid-hal-iyokan-kernel-modules
Requires: droid-config-iyokan-sailfish
Requires: droid-config-iyokan-pulseaudio-settings
Requires: droid-config-iyokan-policy-settings
Requires: droid-config-iyokan-preinit-plugin
Requires: droid-hal-version-iyokan

%description -n patterns-sailfish-device-adaptation-iyokan
Pattern with packages for iyokan HW Adaptation

%files -n patterns-sailfish-device-adaptation-iyokan
